-- Copyright (c) 2026 Stefano Dal Pra stefano.dalpra@cnaf.infn.it
-- Licensed under the EUPL 1.2 License. See LICENSE file in the
-- project root for full license information.

---------------------------------------
-- SCHEMAS AND OWNERS
---------------------------------------

CREATE SCHEMA api;
CREATE SCHEMA sec;

ALTER SCHEMA api OWNER TO api_owner;
ALTER SCHEMA sec OWNER TO pgsodium_admin;

-- Funzioni SEC (needed for EdDSA)
-- sec.base64url_encode(bytea), sec.base64url(jsonb),
-- sec.add_jwt_claims(json,int),
-- sec.derive_eddsa_privkey(int), sec.derive_eddsa_pubkey(int),
-- sec.sign_jwt_eddsa(jsonb,int,int default 2)
-- Owner: pgsodium_admin (or sec_owner).

-- API tables
CREATE TABLE api.users (
  id      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sub     text NOT NULL UNIQUE,
  email   text NOT NULL UNIQUE,
  fname   varchar(128),
  gname   varchar(128)
);
ALTER TABLE api.users OWNER TO api_owner;

CREATE TABLE api.events (
  id      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ts      timestamp NOT NULL DEFAULT now(),
  user_id text NOT NULL,
  event   text NOT NULL,
  "json"  jsonb
);
ALTER TABLE api.events OWNER TO api_owner;
ALTER TABLE api.events
  ADD CONSTRAINT events_user_fk FOREIGN KEY (user_id)
  REFERENCES api.users(sub) ON UPDATE CASCADE ON DELETE RESTRICT;

CREATE TABLE api.mbox (
  id           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "json"       jsonb,
  igwn_bearer  text,
  created      timestamp DEFAULT now(),
  expire       timestamp,
  igwn_jwt     text,
  claims       jsonb
);
ALTER TABLE api.mbox OWNER TO api_owner;

-- for search in jsonb data
CREATE INDEX mbox_claims_iss_sub_idx
  ON api.mbox ((claims->>'iss'), (claims->>'sub'));

-- Funzioni API
-- api.jwt_decode(jwt text)  (SECURITY DEFINER nel dump; portala a OWNER api_owner)
-- api.register_my_jwt()     (SECURITY DEFINER; OWNER api_owner)
-- api.get_iam_jwt(jsonb)    (SECURITY DEFINER; OWNER api_owner)
-- api.mbox_eddsa_insert()   (SECURITY DEFINER; OWNER api_owner)
-- >>> INCOLLA i corpi dal dump; cambia OWNER da sdp → api_owner dove serve. [1](https://istnazfisnucl-my.sharepoint.com/personal/dalpra_infn_it/Documents/Microsoft%20Copilot%20Chat%20Files/prest_schemaonly.sql)

-- Trigger (EdDSA)
CREATE TRIGGER mbox_eddsa_bi
BEFORE INSERT ON api.mbox
FOR EACH ROW EXECUTE FUNCTION api.mbox_eddsa_insert();

-- minimal GRANT 
GRANT USAGE ON SCHEMA api TO anon;  -- extend to custom roles (virgo/ligo/hfdf/igwn) if needed
GRANT EXECUTE ON FUNCTION api.register_my_jwt() TO anon;
-- Who can obtain an IAM JWT:
GRANT EXECUTE ON FUNCTION api.get_iam_jwt(jsonb) TO virgo, ligo, hfdf;
-- (Adapt to actually used roles)


---------------------------------------
-- FUNCTIONS sec.* needed for EdDSA
---------------------------------------

-- add_jwt_claims(json,int)
CREATE OR REPLACE FUNCTION sec.add_jwt_claims(payload json, duration_seconds integer DEFAULT 300)
RETURNS json
LANGUAGE plpgsql SECURITY DEFINER
SET search_path TO 'pgsodium','pg_catalog','public'
AS $$
DECLARE
  now_epoch BIGINT := FLOOR(EXTRACT(EPOCH FROM NOW()));
  out json;
BEGIN
  out := COALESCE(payload, '{}'::json);
  out := out::jsonb || jsonb_build_object(
    'iat', now_epoch,
    'nbf', now_epoch,
    'exp', (now_epoch + greatest(0,duration_seconds))
  );
  RETURN out::json;
END;
$$;
ALTER FUNCTION sec.add_jwt_claims(payload json, duration_seconds integer) OWNER TO pgsodium_admin;

-- base64url_encode(bytea)
CREATE OR REPLACE FUNCTION sec.base64url_encode(data bytea)
RETURNS text
LANGUAGE sql IMMUTABLE
AS $$
  SELECT replace(replace(rtrim(regexp_replace(encode($1,'base64'), E'[\\r\\n]+','','g'),'='),'+','-'),'/','_');
$$;
ALTER FUNCTION sec.base64url_encode(data bytea) OWNER TO sec_owner;

-- base64url(jsonb)
CREATE OR REPLACE FUNCTION sec.base64url(json_in jsonb)
RETURNS text
LANGUAGE sql IMMUTABLE
AS $$
  SELECT sec.base64url_encode(convert_to($1::text,'utf8'));
$$;
ALTER FUNCTION sec.base64url(json_in jsonb) OWNER TO sec_owner;

-- derive_eddsa_privkey(int)
CREATE OR REPLACE FUNCTION sec.derive_eddsa_privkey(key_id integer)
RETURNS bytea
LANGUAGE sql SECURITY DEFINER
SET search_path TO 'pgsodium','pg_catalog','public'
AS $$
  SELECT secret
  FROM pgsodium.crypto_sign_seed_new_keypair(pgsodium.derive_key(key_id));
$$;
ALTER FUNCTION sec.derive_eddsa_privkey(key_id integer) OWNER TO pgsodium_admin;

-- derive_eddsa_pubkey(int)
CREATE OR REPLACE FUNCTION sec.derive_eddsa_pubkey(key_id integer)
RETURNS bytea
LANGUAGE sql SECURITY DEFINER
SET search_path TO 'sec','public'
AS $$
  SELECT public
  FROM pgsodium.crypto_sign_seed_new_keypair(pgsodium.derive_key(key_id));
$$;
ALTER FUNCTION sec.derive_eddsa_pubkey(key_id integer) OWNER TO sec_owner;

-- export_eddsa_jwk(int, text)  (utile per pubblicare JWKS a PostgREST)
CREATE OR REPLACE FUNCTION sec.export_eddsa_jwk(keypair_id integer, kid text DEFAULT NULL)
RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER
SET search_path TO 'sec','public'
AS $$
DECLARE
  pk bytea;
  x_b64 text;
  kid_eff text := COALESCE(kid, 'ed25519-' || keypair_id::text);
BEGIN
  pk := sec.derive_eddsa_pubkey(keypair_id);
  x_b64 := sec.base64url_encode(pk);
  RETURN jsonb_build_object(
    'kty','OKP',
    'crv','Ed25519',
    'x',  x_b64,
    'kid',kid_eff,
    'use','sig',
    'alg','EdDSA'
  );
END;
$$;
ALTER FUNCTION sec.export_eddsa_jwk(keypair_id integer, kid text) OWNER TO sec_owner;

-- sign_jwt_eddsa(jsonb, int, int)
CREATE OR REPLACE FUNCTION sec.sign_jwt_eddsa(jwt jsonb, p_expires_in_seconds integer, keypair_id integer DEFAULT 2)
RETURNS text
LANGUAGE plpgsql SECURITY DEFINER
SET search_path TO 'sec','public'
AS $$
DECLARE
  kid text := 'ed25519-' || keypair_id::text;
  header_json  jsonb;
  payload_json jsonb;
  b64header text;
  b64payload text;
  signing_input text;
  sk bytea;
  sig bytea;
  b64sig text;
BEGIN
  payload_json := (sec.add_jwt_claims(jwt::json, p_expires_in_seconds))::jsonb;
  header_json  := jsonb_build_object('alg','EdDSA','typ','JWT','kid', kid);

  b64header  := sec.base64url(header_json);
  b64payload := sec.base64url(payload_json);
  signing_input := b64header || '.' || b64payload;

  sk := sec.derive_eddsa_privkey(keypair_id);
  sig := pgsodium.crypto_sign_detached(convert_to(signing_input,'utf8'), sk);
  b64sig := sec.base64url_encode(sig);

  -- hardening (whitespace unlikely ma innocuo)
  b64header  := regexp_replace(b64header,  '\s', '', 'g');
  b64payload := regexp_replace(b64payload, '\s', '', 'g');
  b64sig     := regexp_replace(b64sig,     '\s', '', 'g');

  RETURN b64header || '.' || b64payload || '.' || b64sig;
END;
$$;
ALTER FUNCTION sec.sign_jwt_eddsa(jwt jsonb, p_expires_in_seconds integer, keypair_id integer) OWNER TO pgsodium_admin;

---------------------------------------
-- api.* FUNCTIONS 
---------------------------------------

-- jwt_decode(text)
CREATE OR REPLACE FUNCTION api.jwt_decode(jwt text)
RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER
AS $$
DECLARE
  t_enc TEXT := split_part(jwt, '.', 2);
  tpad  INT;
BEGIN
  t_enc := regexp_replace(t_enc, '\s', '', 'g');
  t_enc := replace(replace(t_enc, '-', '+'), '_', '/');
  tpad  := (4 - length(t_enc) % 4) % 4;
  IF tpad > 0 THEN
    t_enc := t_enc || repeat('=', tpad);
  END IF;
  RETURN convert_from(decode(t_enc, 'base64'), 'UTF8')::jsonb;
END;
$$;
ALTER FUNCTION api.jwt_decode(jwt text) OWNER TO api_owner;
REVOKE ALL ON FUNCTION api.jwt_decode(jwt text) FROM PUBLIC;

-- mbox_eddsa_insert()  (trigger)
CREATE OR REPLACE FUNCTION api.mbox_eddsa_insert()
RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER
SET search_path TO 'pg_catalog','public','api','sec'
AS $$
DECLARE
  clear_jwt  jsonb := api.jwt_decode(NEW.igwn_bearer);
  claims_jwt jsonb := clear_jwt - '{nbf,exp,iat,jti,client_id,wlcg.ver}'::text[];
  role_text  text;
  payload    jsonb;
BEGIN
  --  role: first wlcg.groups element if present
  --  'virgo' otherwise
  role_text := ltrim(coalesce(claims_jwt['wlcg.groups']->>0,'/virgo'),'/');

  payload := (claims_jwt || jsonb_build_object(
    'aud','vacct',
    'iss','gems',
    'role', role_text
  ))::jsonb;

  NEW.claims  := claims_jwt;
  NEW.expire  := (claims_jwt->>'exp');
  NEW.igwn_jwt := sec.sign_jwt_eddsa(
    jwt := payload,
    p_expires_in_seconds := 7 * 86400,
    keypair_id := 2
  );

  RETURN NEW;
END
$$;
ALTER FUNCTION api.mbox_eddsa_insert() OWNER TO api_owner;
REVOKE ALL ON FUNCTION api.mbox_eddsa_insert() FROM PUBLIC;

-- register_my_jwt()  -- to be invoked as anon role
CREATE OR REPLACE FUNCTION api.register_my_jwt()
 RETURNS text
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'api', 'sec', 'pg_catalog', 'public'
AS $function$
DECLARE
  -- 1) Header Authorization (from PostgREST request context)
  _hdrs   jsonb := current_setting('request.headers', true)::jsonb;  -- headers JSON
  _auth   text  := coalesce(_hdrs->>'authorization', '');
  _bearer text;

  -- 2) clean external JWT claims
  clear_jwt  jsonb;
  claims_jwt jsonb;

  -- 3) user data
  v_sub   text;
  v_email text;

  -- 4) computed role + payload to be signed
  role_text  text;
  payload    jsonb;

  -- 5) current existing mbox entry
  v_id       integer;
  v_expire   timestamp;
  v_igwn_jwt text;

  -- 6) New values
  new_expire timestamp := now() + interval '7 days';
  new_jwt    text;

  -- 7) event tracking
  ev_text    text;
BEGIN
  -- mandatory authorization 
  IF _auth IS NULL OR _auth = '' THEN
    RAISE EXCEPTION 'Missing Authorization header';
  END IF;

  -- "Bearer <token>"
  _bearer := btrim(regexp_replace(_auth, '^\s*Bearer\s+', '', 1, 1, 'i'));

  -- Decoding IAM JWT (payload)
  clear_jwt  := api.jwt_decode(_bearer);
  claims_jwt := jsonb_pick(clear_jwt, '{aud,sub,iss,scope,wlcg.groups,role}');

  -- Extract sub/email for user check
  v_sub   := claims_jwt->>'sub';
  v_email := claims_jwt->>'email';

  IF v_sub IS NULL OR v_sub = '' THEN
    RAISE EXCEPTION 'JWT is missing "sub" claim';
  END IF;

  -- Only allow registered users
  PERFORM 1 FROM api.users WHERE sub = v_sub;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'User "%" is not registered (missing in api.users)', v_sub;
  END IF;

  role_text := coalesce(split_part(claims_jwt['wlcg.groups']->>0,'/',2),'anon');
  -- internal payload to be signed (aud/iss/role fixed)
  payload := (claims_jwt ||
              jsonb_build_object('aud','vacct','iss','gems','role',role_text))::jsonb;

  -- find a matching row in mbox
  SELECT id, expire, igwn_jwt
    INTO v_id, v_expire, v_igwn_jwt
  FROM api.mbox
  WHERE claims->>'iss' = claims_jwt->>'iss'
    AND claims->>'sub' = claims_jwt->>'sub'
    AND claims->'scope' = claims_jwt->'scope'
    AND claims->'wlcg.groups' = claims_jwt->'wlcg.groups'
  LIMIT 1;

  IF v_id IS NOT NULL THEN
    -- match found: decide if new signature needed
    IF v_expire IS NULL OR v_expire <= now() + interval '3.5 days' THEN
      -- Renew EdDSA signature (3 days)
      new_jwt := sec.sign_jwt_eddsa(
                   jwt                  := payload,
                   p_expires_in_seconds := 3 * 86400,
                   keypair_id           := 2
                 );

      UPDATE api.mbox
         SET igwn_bearer = _bearer,
             igwn_jwt    = new_jwt,
             claims      = claims_jwt,
             expire      = new_expire
       WHERE id = v_id;

      ev_text := format('mbox:renew sub=%s, iss=%s (expire <= 2d)', v_sub, claims_jwt->>'iss');
      INSERT INTO api.events(user_id, event) VALUES (v_sub, ev_text);
      RETURN new_jwt;
    ELSE
      -- Still valid: reusing existing token
      UPDATE api.mbox
         SET igwn_bearer = _bearer,
             claims      = claims_jwt
       WHERE id = v_id;

      ev_text := format('mbox:reuse sub=%s, iss=%s', v_sub, claims_jwt->>'iss');
      INSERT INTO api.events(user_id, event) VALUES (v_sub, ev_text);

      RETURN v_igwn_jwt;
    END IF;

  ELSE
    -- New mbox row: signature EdDSA (3 days)
    new_jwt := sec.sign_jwt_eddsa(
                 jwt                  := payload,
                 p_expires_in_seconds := 3 * 86400,
                 keypair_id           := 2
               );

    INSERT INTO api.mbox (igwn_bearer, claims, igwn_jwt, expire)
    VALUES (_bearer, claims_jwt, new_jwt, new_expire);

    ev_text := format('mbox:new sub=%s, iss=%s', v_sub, claims_jwt->>'iss');
    INSERT INTO api.events(user_id, event) VALUES (v_sub, ev_text);

    RETURN new_jwt;
  END IF;
END
$function$;

ALTER FUNCTION api.register_my_jwt() OWNER TO api_owner;
REVOKE ALL ON FUNCTION api.register_my_jwt() FROM PUBLIC;

-- get_iam_jwt(message jsonb) 
CREATE OR REPLACE FUNCTION api.get_iam_jwt(message jsonb)
 RETURNS text
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'api', 'sec', 'public'
AS $function$
DECLARE
  -- token claims (IGWN / IAM JWT) from PostgREST call context
  jcs        jsonb := current_setting('request.jwt.claims', true)::jsonb;
  now_epoch  integer := extract(epoch from now())::integer;

  -- Candidate mbox new row
  v_id       integer;
  v_igwn_bearer text;
  v_claims   jsonb;
  v_jbt      jsonb;    -- bearer payload (IAM_JWT) decoded
  v_expire   timestamp;

  -- users's Sub
  v_sub      text;

  -- Event
  ev_text    text;

-- for debugging;
  dbg jsonb;
BEGIN
  /* 0) Validating input & user */
  IF jcs IS NULL THEN
    RAISE EXCEPTION 'Missing request.jwt.claims (no IGWN_JWT provided)';
  END IF;

  -- jobid and runtime must be present
  IF message IS NULL OR NOT (message ? 'jobid') OR NOT (message ? 'runtime') THEN
    RAISE EXCEPTION 'Invalid message: "jobid" and "runtime" are required';
  END IF;

  v_sub := jcs->>'sub';
  IF v_sub IS NULL OR v_sub = '' THEN
    RAISE EXCEPTION 'Current IGWN_JWT has no "sub" claim';
  END IF;

  -- l’utente deve esistere in api.users
  PERFORM 1 FROM api.users WHERE sub = v_sub;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'User "%" is not registered in api.users', v_sub;
  END IF;

WITH a AS (
         SELECT mbox.*,
            api.jwt_decode(mbox.igwn_bearer) AS jbt,
            api.jwt_decode(mbox.igwn_jwt) AS jwt,
            current_setting('request.jwt.claims'::text, true)::jsonb AS jcs,
            EXTRACT(epoch FROM now())::integer AS now_epoch
           FROM api.mbox
          ORDER BY mbox.id DESC
        ), b AS (
         SELECT a.*
           FROM a
          WHERE ((a.jbt ->> 'exp'::text)::integer) > (a.now_epoch + 600)
            AND jsonb_pick(a.jbt, '{aud,sub,iss,scope,wlcg.groups}') = jsonb_pick(a.claims, '{aud,sub,iss,scope,wlcg.groups}')
            AND (a.jcs ->> 'sub'::text) = (a.claims ->> 'sub'::text)
          ORDER BY a.id DESC
         LIMIT 1
        )
 SELECT id,igwn_bearer,claims,expire
   INTO v_id, v_igwn_bearer, v_claims, v_expire
   FROM b;

 -- RAISE NOTICE 'id = %',v_id;
  IF v_id IS NULL THEN
    -- RAISE EXCEPTION 'No mbox entry found for subject "%"', v_sub;
   RAISE EXCEPTION 'NO MATCH: "%" , "%"', jcs::text, m.claims::text;
  END IF;

  /* 2) Verifica consistenza con l’IAM_JWT salvato (igwn_bearer) */
  v_jbt := api.jwt_decode(v_igwn_bearer);

  -- stesso controllo della view: exp > now + 600s e payload "ridotto" uguale a claims
  IF ( (v_jbt->>'exp')::integer <= (now_epoch + 600)
       OR (v_jbt - '{wlcg.ver,nbf,exp,iat,jti,client_id}'::text[]) <> v_claims ) THEN
    RAISE EXCEPTION 'No valid IAM_JWT found (expired or claims mismatch) for subject "%"', v_sub;
  END IF;
  /* 3) Tracking event */
  ev_text := format(
              'iam_jwt:served sub=%s, iss=%s, expires_in=%ss',
              v_sub, v_claims->>'iss', (v_jbt->>'exp')::integer - now_epoch
            );

  INSERT INTO api.events(user_id, event, json)
  VALUES (v_sub, ev_text, message);

  /* 4) Return IAM_JWT */
  RETURN v_igwn_bearer;
END
$function$;

ALTER FUNCTION api.get_iam_jwt(message jsonb) OWNER TO api_owner;
REVOKE ALL ON FUNCTION api.get_iam_jwt(message jsonb) FROM PUBLIC;

---------------------------------------
-- TRIGGER (EdDSA only)
---------------------------------------
CREATE TRIGGER mbox_eddsa_bi
BEFORE INSERT ON api.mbox
FOR EACH ROW EXECUTE FUNCTION api.mbox_eddsa_insert();

---------------------------------------
-- GRANTS (MINIMUM) (no direct grant on tables)
---------------------------------------
-- Schema api usable by roles 
GRANT USAGE ON SCHEMA api TO anon, virgo, igwn;

GRANT EXECUTE ON FUNCTION api.register_my_jwt()           TO anon;
GRANT EXECUTE ON FUNCTION api.get_iam_jwt(message jsonb)  TO virgo, igwn;
